export function zodiacInfo(sign) {
	const signs = {
		Aries: {
			name: "Овен",
			element: "Огонь",
			quality: "Кардинальный",
			ruler: "Марс",
			color: "Красный",
			day: "Вторник",
			luckyNumbers: "1, 8, 17",
			flowers: "Красная роза, Тюльпан",
			gemstones: "Кровавик, Алмаз",
			strengths: "Смелость, решительность, энергичность",
			weaknesses: "Импульсивность, нетерпимость, агрессивность",
			likes: "Физические задачи, приключения, спорт",
			dislikes: "Ожидание, бездействие, работа в команде",
			favoriteActivities: "Спорт, путешествия, лидерские задачи",
			positiveTraits: "Смелость, инициативность, энтузиазм",
			negativeTraits: "Импульсивность, агрессивность, нетерпение",
			compatibleSigns: "Лев, Стрелец",
			incompatibleSigns: "Рак, Козерог",
			birthstone: "Алмаз",
			metal: "Железо",
			luckyDay: "Вторник",
			tarotCard: "Император",
			animal: "Баран",
			season: "Весна",
			motto: "Я есть",
			bodyPart: "Голова",
			energy: "Ян",
			polarity: "Мужской",
			spiritColor: "Красный",
			powerStone: "Гранат",
			elementSymbol: "Овен",
			chakra: "Муладхара (Корневая)",
			positiveKeywords: "Смелый, энергичный, независимый",
			negativeKeywords: "Импульсивный, нетерпеливый, агрессивный",
			archetype: "Воин",
			spiritualAnimal: "Ястреб",
			luckyCharm: "Амулет",
			favoriteFood: "Мясо, острые блюда",
			favoriteDrink: "Кофе, энергетические напитки",
			favoriteMusic: "Рок, метал",
			favoriteSport: "Бег, боевые искусства",
			favoriteHobby: "Физические упражнения, соревновательные игры",
			famousPeople: "Леонардо да Винчи, Чарли Чаплин",
			luckyFlower: "Пион",
			rulingPlanet: "Марс",
			favorableMonth: "Март",
			keyStrength: "Энергия",
			keyWeakness: "Импульсивность",
		},
		Taurus: {
			name: "Телец",
			element: "Земля",
			quality: "Фиксированный",
			ruler: "Венера",
			color: "Зеленый",
			day: "Пятница",
			luckyNumbers: "2, 6, 9, 12, 24",
			flowers: "Роза, Маки",
			gemstones: "Сапфир, Изумруд",
			strengths: "Надежность, терпеливость, решительность",
			weaknesses: "Упрямство, собственничество, консерватизм",
			likes: "Садоводство, кулинария, музыка",
			dislikes: "Изменения, неопределенность, искусственные вещи",
			favoriteActivities: "Садоводство, готовка, прослушивание музыки",
			positiveTraits: "Надежность, терпеливость, решительность",
			negativeTraits: "Упрямство, собственничество, консерватизм",
			compatibleSigns: "Дева, Козерог",
			incompatibleSigns: "Лев, Водолей",
			birthstone: "Изумруд",
			metal: "Медь",
			luckyDay: "Пятница",
			tarotCard: "Иерофант",
			animal: "Бык",
			season: "Весна",
			motto: "Я имею",
			bodyPart: "Шея, горло",
			energy: "Инь",
			polarity: "Женский",
			spiritColor: "Розовый",
			powerStone: "Розовый кварц",
			elementSymbol: "Телец",
			chakra: "Свадхистана (Сакральная)",
			positiveKeywords: "Надежный, терпеливый, решительный",
			negativeKeywords: "Упрямый, собственнический, консервативный",
			archetype: "Строитель",
			spiritualAnimal: "Медведь",
			luckyCharm: "Талисман",
			favoriteFood: "Сытные блюда, сладости",
			favoriteDrink: "Вино, молочные коктейли",
			favoriteMusic: "Классическая, джаз",
			favoriteSport: "Йога, ходьба",
			favoriteHobby: "Готовка, садоводство",
			famousPeople: "Шекспир, Одри Хепберн",
			luckyFlower: "Гвоздика",
			rulingPlanet: "Венера",
			favorableMonth: "Май",
			keyStrength: "Стабильность",
			keyWeakness: "Собственничество",
		},
		Gemini: {
			name: "Близнецы",
			element: "Воздух",
			quality: "Переменный",
			ruler: "Меркурий",
			color: "Желтый",
			day: "Среда",
			luckyNumbers: "5, 7, 14, 23",
			flowers: "Лаванда, Ландыш",
			gemstones: "Агат, Аквамарин",
			strengths: "Нежность, дружелюбие, открытость",
			weaknesses: "Нервозность, непоследовательность, нерешительность",
			likes: "Разговоры, приключения, новые впечатления",
			dislikes: "Рутина, одиночество, ограничения",
			favoriteActivities: "Путешествия, чтение, социальные мероприятия",
			positiveTraits: "Остроумие, любознательность, адаптивность",
			negativeTraits: "Беспокойство, поверхностность, непредсказуемость",
			compatibleSigns: "Весы, Водолей",
			incompatibleSigns: "Рыбы, Дева",
			birthstone: "Жемчуг",
			metal: "Ртуть",
			luckyDay: "Среда",
			tarotCard: "Влюбленные",
			animal: "Обезьяна",
			season: "Весна",
			motto: "Я думаю",
			bodyPart: "Руки, легкие",
			energy: "Ян",
			polarity: "Мужской",
			spiritColor: "Светло-зеленый",
			powerStone: "Цитрин",
			elementSymbol: "Близнецы",
			chakra: "Вишуддха (Горловая)",
			positiveKeywords: "Умный, многозадачный, гибкий",
			negativeKeywords: "Непоследовательный, поверхностный, нервный",
			archetype: "Коммуникатор",
			spiritualAnimal: "Бабочка",
			luckyCharm: "Подкова",
			favoriteFood: "Фрукты, легкие закуски",
			favoriteDrink: "Чай, сок",
			favoriteMusic: "Поп, электроника",
			favoriteSport: "Бег, теннис",
			favoriteHobby: "Чтение, писательство",
			famousPeople: "Анджелина Джоли, Джонни Депп",
			luckyFlower: "Маргаритка",
			rulingPlanet: "Меркурий",
			favorableMonth: "Июнь",
			keyStrength: "Коммуникация",
			keyWeakness: "Непоследовательность",
		},
		Cancer: {
			name: "Рак",
			element: "Вода",
			quality: "Кардинальный",
			ruler: "Луна",
			color: "Белый",
			day: "Понедельник",
			luckyNumbers: "2, 3, 15, 20",
			flowers: "Лилия, Жасмин",
			gemstones: "Изумруд, Лунный камень",
			strengths: "Лояльность, креативность, эмоциональность",
			weaknesses: "Настроение, пессимизм, подозрительность",
			likes: "Искусство, дом, вода",
			dislikes: "Незнакомцы, критика матери, раскрытие личной жизни",
			favoriteActivities: "Искусство, кулинария, рукоделие",
			positiveTraits: "Лояльность, заботливость, креативность",
			negativeTraits: "Настроение, пессимизм, подозрительность",
			compatibleSigns: "Скорпион, Рыбы",
			incompatibleSigns: "Овен, Весы",
			birthstone: "Рубин",
			metal: "Серебро",
			luckyDay: "Понедельник",
			tarotCard: "Колесница",
			animal: "Краб",
			season: "Лето",
			motto: "Я чувствую",
			bodyPart: "Грудь, желудок",
			energy: "Инь",
			polarity: "Женский",
			spiritColor: "Серебристый",
			powerStone: "Лунный камень",
			elementSymbol: "Рак",
			chakra: "Анахата (Сердечная)",
			positiveKeywords: "Заботливый, интуитивный, креативный",
			negativeKeywords: "Настроение, пессимизм, подозрительность",
			archetype: "Мать",
			spiritualAnimal: "Лебедь",
			luckyCharm: "Лунный амулет",
			favoriteFood: "Морепродукты, домашняя еда",
			favoriteDrink: "Сок, вода",
			favoriteMusic: "Классическая, народная",
			favoriteSport: "Плавание, йога",
			favoriteHobby: "Готовка, рисование",
			famousPeople: "Том Хэнкс, Принцесса Диана",
			luckyFlower: "Гардения",
			rulingPlanet: "Луна",
			favorableMonth: "Июль",
			keyStrength: "Сочувствие",
			keyWeakness: "Чрезмерная эмоциональность",
		},
		Leo: {
			name: "Лев",
			element: "Огонь",
			quality: "Фиксированный",
			ruler: "Солнце",
			color: "Золотой",
			day: "Воскресенье",
			luckyNumbers: "1, 3, 10, 19",
			flowers: "Подсолнух, календула",
			gemstones: "Рубин, Янтарь",
			strengths: "Щедрость, теплота, креативность",
			weaknesses: "Высокомерие, упрямство, неуверенность",
			likes: "Театр, праздники, внимание",
			dislikes: "Игнорирование, конфронтация, скука",
			favoriteActivities: "Театр, творчество, спорт",
			positiveTraits: "Щедрость, креативность, лидерство",
			negativeTraits: "Высокомерие, упрямство, неуверенность",
			compatibleSigns: "Овен, Стрелец",
			incompatibleSigns: "Телец, Скорпион",
			birthstone: "Рубин",
			metal: "Золото",
			luckyDay: "Воскресенье",
			tarotCard: "Сила",
			animal: "Лев",
			season: "Лето",
			motto: "Я воля",
			bodyPart: "Сердце, позвоночник",
			energy: "Ян",
			polarity: "Мужской",
			spiritColor: "Золотой",
			powerStone: "Янтарь",
			elementSymbol: "Лев",
			chakra: "Свадхистана (Сакральная)",
			positiveKeywords: "Креативный, щедрый, лидер",
			negativeKeywords: "Высокомерный, упрямый, неуверенный",
			archetype: "Король",
			spiritualAnimal: "Лев",
			luckyCharm: "Золотой амулет",
			favoriteFood: "Экзотическая еда, мясо",
			favoriteDrink: "Шампанское, соки",
			favoriteMusic: "Поп, классическая",
			favoriteSport: "Футбол, теннис",
			favoriteHobby: "Театр, творчество",
			famousPeople: "Мадонна, Дженнифер Лопес",
			luckyFlower: "Роза",
			rulingPlanet: "Солнце",
			favorableMonth: "Август",
			keyStrength: "Лидерство",
			keyWeakness: "Эгоцентризм",
		},
		Virgo: {
			name: "Дева",
			element: "Земля",
			quality: "Переменный",
			ruler: "Меркурий",
			color: "Синий",
			day: "Среда",
			luckyNumbers: "5, 14, 15, 23, 32",
			flowers: "Ромашка, Лаванда",
			gemstones: "Сапфир, Нефрит",
			strengths: "Аналитичность, внимательность, надежность",
			weaknesses: "Критичность, замкнутость, чрезмерная забота о деталях",
			likes: "Чистота, здоровье, книги",
			dislikes: "Грязь, беспорядок, неопределенность",
			favoriteActivities: "Чтение, медитация, уход за садом",
			positiveTraits: "Аналитичность, внимательность, надежность",
			negativeTraits: "Критичность, замкнутость, чрезмерная забота о деталях",
			compatibleSigns: "Телец, Козерог",
			incompatibleSigns: "Близнецы, Стрелец",
			birthstone: "Сапфир",
			metal: "Ртуть",
			luckyDay: "Среда",
			tarotCard: "Отшельник",
			animal: "Лисица",
			season: "Осень",
			motto: "Я анализирую",
			bodyPart: "Живот",
			energy: "Инь",
			polarity: "Женский",
			spiritColor: "Синий",
			powerStone: "Нефрит",
			elementSymbol: "Дева",
			chakra: "Манипура (Солнечное сплетение)",
			positiveKeywords: "Организованный, внимательный, надежный",
			negativeKeywords: "Критичный, замкнутый, чрезмерно заботящийся о деталях",
			archetype: "Исследователь",
			spiritualAnimal: "Лиса",
			luckyCharm: "Четырёхлистный клевер",
			favoriteFood: "Органическая еда, полезные блюда",
			favoriteDrink: "Чай, травяные настои",
			favoriteMusic: "Классическая, инструментальная",
			favoriteSport: "Йога, пилатес",
			favoriteHobby: "Чтение, садоводство",
			famousPeople: "Бейонсе, Майкл Джексон",
			luckyFlower: "Подсолнух",
			rulingPlanet: "Меркурий",
			favorableMonth: "Сентябрь",
			keyStrength: "Детализация",
			keyWeakness: "Критичность",
		},
		Libra: {
			name: "Весы",
			element: "Воздух",
			quality: "Кардинальный",
			ruler: "Венера",
			color: "Розовый",
			day: "Пятница",
			luckyNumbers: "4, 6, 13, 15, 24",
			flowers: "Роза, Лилия",
			gemstones: "Опал, Изумруд",
			strengths: "Дипломатичность, обаяние, справедливость",
			weaknesses:
				"Нерешительность, избегание конфликтов, склонность к самоудовлетворению",
			likes: "Гармония, искусство, общение",
			dislikes: "Несправедливость, грубость, конфликты",
			favoriteActivities: "Социальные мероприятия, искусство, шопинг",
			positiveTraits: "Дипломатичность, обаяние, справедливость",
			negativeTraits:
				"Нерешительность, избегание конфликтов, склонность к самоудовлетворению",
			compatibleSigns: "Близнецы, Водолей",
			incompatibleSigns: "Рак, Козерог",
			birthstone: "Опал",
			metal: "Медь",
			luckyDay: "Пятница",
			tarotCard: "Справедливость",
			animal: "Лебедь",
			season: "Осень",
			motto: "Я уравновешиваю",
			bodyPart: "Почки, поясница",
			energy: "Ян",
			polarity: "Мужской",
			spiritColor: "Розовый",
			powerStone: "Розовый кварц",
			elementSymbol: "Весы",
			chakra: "Анахата (Сердечная)",
			positiveKeywords: "Обаяние, справедливость, дипломатичность",
			negativeKeywords:
				"Нерешительность, избегание конфликтов, склонность к самоудовлетворению",
			archetype: "Дипломат",
			spiritualAnimal: "Лебедь",
			luckyCharm: "Подкова",
			favoriteFood: "Изящные блюда, десерты",
			favoriteDrink: "Коктейли, чай",
			favoriteMusic: "Классическая, джаз",
			favoriteSport: "Танцы, теннис",
			favoriteHobby: "Искусство, мода",
			famousPeople: "Уилл Смит, Гвен Стефани",
			luckyFlower: "Орхидея",
			rulingPlanet: "Венера",
			favorableMonth: "Октябрь",
			keyStrength: "Гармония",
			keyWeakness: "Нерешительность",
		},
		Scorpio: {
			name: "Скорпион",
			element: "Вода",
			quality: "Фиксированный",
			ruler: "Плутон",
			color: "Чёрный",
			day: "Вторник",
			luckyNumbers: "8, 11, 18, 22",
			flowers: "Хризантема, Гардения",
			gemstones: "Топаз, Обсидиан",
			strengths: "Решительность, храбрость, страстность",
			weaknesses: "Ревнивость, скрытность, упрямство",
			likes: "Истина, факты, долгосрочные друзья",
			dislikes: "Ложь, пассивность, откровенность",
			favoriteActivities: "Исследование, творчество, изучение тайн",
			positiveTraits: "Решительность, страстность, наблюдательность",
			negativeTraits: "Ревнивость, скрытность, упрямство",
			compatibleSigns: "Рак, Рыбы",
			incompatibleSigns: "Лев, Водолей",
			birthstone: "Топаз",
			metal: "Железо",
			luckyDay: "Вторник",
			tarotCard: "Смерть",
			animal: "Скорпион",
			season: "Осень",
			motto: "Я желаю",
			bodyPart: "Половые органы",
			energy: "Инь",
			polarity: "Женский",
			spiritColor: "Темно-красный",
			powerStone: "Обсидиан",
			elementSymbol: "Скорпион",
			chakra: "Свадхистана (Сакральная)",
			positiveKeywords: "Страстный, решительный, наблюдательный",
			negativeKeywords: "Ревнивый, скрытный, упрямый",
			archetype: "Алхимик",
			spiritualAnimal: "Орел",
			luckyCharm: "Скорпион",
			favoriteFood: "Острая еда, экзотические блюда",
			favoriteDrink: "Крепкие напитки, чай",
			favoriteMusic: "Рок, драматическая",
			favoriteSport: "Боевые искусства, экстремальные виды спорта",
			favoriteHobby: "Исследования, творчество",
			famousPeople: "Билл Гейтс, Леонардо ДиКаприо",
			luckyFlower: "Роза",
			rulingPlanet: "Плутон",
			favorableMonth: "Ноябрь",
			keyStrength: "Интенсивность",
			keyWeakness: "Ревность",
		},
		Sagittarius: {
			name: "Стрелец",
			element: "Огонь",
			quality: "Переменный",
			ruler: "Юпитер",
			color: "Фиолетовый",
			day: "Четверг",
			luckyNumbers: "3, 7, 9, 12, 21",
			flowers: "Нарцисс, Пион",
			gemstones: "Бирюза, Топаз",
			strengths: "Щедрость, идеализм, чувство юмора",
			weaknesses: "Обещания больше, чем можно выполнить, нетактичность",
			likes: "Путешествия, философия, нахождение на улице",
			dislikes: "Замкнутость, ограниченность, придирки",
			favoriteActivities: "Путешествия, спорт, обучение",
			positiveTraits: "Щедрость, идеализм, юмор",
			negativeTraits: "Нетактичность, обещания больше, чем можно выполнить",
			compatibleSigns: "Овен, Лев",
			incompatibleSigns: "Дева, Рыбы",
			birthstone: "Топаз",
			metal: "Олово",
			luckyDay: "Четверг",
			tarotCard: "Умеренность",
			animal: "Кентавр",
			season: "Осень",
			motto: "Я вижу",
			bodyPart: "Бедра, печень",
			energy: "Ян",
			polarity: "Мужской",
			spiritColor: "Синий",
			powerStone: "Бирюза",
			elementSymbol: "Стрелец",
			chakra: "Сахасрара (Коронная)",
			positiveKeywords: "Щедрый, идеалист, веселый",
			negativeKeywords: "Нетактичный, обещания больше, чем можно выполнить",
			archetype: "Путешественник",
			spiritualAnimal: "Лошадь",
			luckyCharm: "Стрела",
			favoriteFood: "Экзотическая еда, мясные блюда",
			favoriteDrink: "Экзотические напитки, соки",
			favoriteMusic: "Этническая, мировая музыка",
			favoriteSport: "Путешествия, спорт",
			favoriteHobby: "Путешествия, обучение",
			famousPeople: "Тейлор Свифт, Брэд Питт",
			luckyFlower: "Гвоздика",
			rulingPlanet: "Юпитер",
			favorableMonth: "Декабрь",
			keyStrength: "Оптимизм",
			keyWeakness: "Нетактичность",
		},
		Capricorn: {
			name: "Козерог",
			element: "Земля",
			quality: "Кардинальный",
			ruler: "Сатурн",
			color: "Коричневый",
			day: "Суббота",
			luckyNumbers: "4, 8, 13, 22",
			flowers: "Гвоздика, Плющ",
			gemstones: "Оникс, Янтарь",
			strengths: "Дисциплина, ответственность, амбициозность",
			weaknesses: "Безжалостность, пессимизм, надменность",
			likes: "Семья, традиции, музыка",
			dislikes: "Беспорядок, обещания без исполнения, несерьезное отношение",
			favoriteActivities: "Работа, отдых на природе, изучение истории",
			positiveTraits: "Дисциплина, ответственность, амбициозность",
			negativeTraits: "Безжалостность, пессимизм, надменность",
			compatibleSigns: "Телец, Дева",
			incompatibleSigns: "Овен, Весы",
			birthstone: "Оникс",
			metal: "Свинец",
			luckyDay: "Суббота",
			tarotCard: "Дьявол",
			animal: "Козел",
			season: "Зима",
			motto: "Я использую",
			bodyPart: "Колени, кости",
			energy: "Инь",
			polarity: "Женский",
			spiritColor: "Коричневый",
			powerStone: "Оникс",
			elementSymbol: "Козерог",
			chakra: "Муладхара (Корневая)",
			positiveKeywords: "Дисциплинированный, ответственный, амбициозный",
			negativeKeywords: "Безжалостный, пессимистичный, надменный",
			archetype: "Стратег",
			spiritualAnimal: "Козел",
			luckyCharm: "Амулет",
			favoriteFood: "Традиционные блюда, мясо",
			favoriteDrink: "Вино, чай",
			favoriteMusic: "Классическая, джаз",
			favoriteSport: "Альпинизм, бег",
			favoriteHobby: "Изучение истории, работа",
			famousPeople: "Мартин Лютер Кинг, Мишель Обама",
			luckyFlower: "Жасмин",
			rulingPlanet: "Сатурн",
			favorableMonth: "Январь",
			keyStrength: "Стабильность",
			keyWeakness: "Жесткость",
		},
		Aquarius: {
			name: "Водолей",
			element: "Воздух",
			quality: "Фиксированный",
			ruler: "Уран",
			color: "Голубой",
			day: "Суббота",
			luckyNumbers: "4, 7, 11, 22, 29",
			flowers: "Орхидея, Лилия",
			gemstones: "Аметист, Янтарь",
			strengths: "Оригинальность, независимость, гуманизм",
			weaknesses: "Упрямство, отстраненность, непредсказуемость",
			likes: "Веселье с друзьями, помощь другим, интеллектуальные беседы",
			dislikes: "Ограничения, обещания без выполнения, одиночество",
			favoriteActivities:
				"Научные исследования, общение с друзьями, волонтерство",
			positiveTraits: "Оригинальность, независимость, гуманизм",
			negativeTraits: "Упрямство, отстраненность, непредсказуемость",
			compatibleSigns: "Близнецы, Весы",
			incompatibleSigns: "Телец, Скорпион",
			birthstone: "Аметист",
			metal: "Уран",
			luckyDay: "Суббота",
			tarotCard: "Звезда",
			animal: "Дельфин",
			season: "Зима",
			motto: "Я знаю",
			bodyPart: "Лодыжки, ноги",
			energy: "Ян",
			polarity: "Мужской",
			spiritColor: "Голубой",
			powerStone: "Аметист",
			elementSymbol: "Водолей",
			chakra: "Аджна (Третий глаз)",
			positiveKeywords: "Оригинальный, независимый, гуманистичный",
			negativeKeywords: "Упрямый, отстраненный, непредсказуемый",
			archetype: "Изобретатель",
			spiritualAnimal: "Дельфин",
			luckyCharm: "Кристалл",
			favoriteFood: "Экзотическая еда, вегетарианские блюда",
			favoriteDrink: "Коктейли, фруктовые соки",
			favoriteMusic: "Электронная, экспериментальная",
			favoriteSport: "Йога, бег",
			favoriteHobby: "Научные исследования, волонтерство",
			famousPeople: "Опра Уинфри, Шакира",
			luckyFlower: "Ирис",
			rulingPlanet: "Уран",
			favorableMonth: "Февраль",
			keyStrength: "Индивидуальность",
			keyWeakness: "Отстраненность",
		},
		Pisces: {
			name: "Рыбы",
			element: "Вода",
			quality: "Переменный",
			ruler: "Нептун",
			color: "Лиловый",
			day: "Четверг",
			luckyNumbers: "3, 9, 12, 15, 18, 24",
			flowers: "Лотос, Лилия",
			gemstones: "Аквамарин, Аметист",
			strengths: "Сочувствие, интуиция, артистизм",
			weaknesses: "Склонность к меланхолии, излишняя доверчивость, пессимизм",
			likes: "Музыка, романтика, сон",
			dislikes: "Жестокость, критика, прошлые неудачи",
			favoriteActivities: "Музыка, мечтание, плавание",
			positiveTraits: "Сочувствие, интуиция, артистизм",
			negativeTraits:
				"Склонность к меланхолии, излишняя доверчивость, пессимизм",
			compatibleSigns: "Рак, Скорпион",
			incompatibleSigns: "Близнецы, Стрелец",
			birthstone: "Аметист",
			metal: "Олово",
			luckyDay: "Четверг",
			tarotCard: "Луна",
			animal: "Рыбы",
			season: "Зима",
			motto: "Я верю",
			bodyPart: "Ступни",
			energy: "Инь",
			polarity: "Женский",
			spiritColor: "Лиловый",
			powerStone: "Аквамарин",
			elementSymbol: "Рыбы",
			chakra: "Сахасрара (Коронная)",
			positiveKeywords: "Сочувствующий, интуитивный, артистичный",
			negativeKeywords:
				"Склонный к меланхолии, излишне доверчивый, пессимистичный",
			archetype: "Мечтатель",
			spiritualAnimal: "Рыбы",
			luckyCharm: "Аметист",
			favoriteFood: "Морепродукты, экзотическая еда",
			favoriteDrink: "Фруктовые соки, коктейли",
			favoriteMusic: "Романтическая, релаксационная",
			favoriteSport: "Плавание, йога",
			favoriteHobby: "Музыка, мечтание",
			famousPeople: "Альберт Эйнштейн, Рианна",
			luckyFlower: "Фиалка",
			rulingPlanet: "Нептун",
			favorableMonth: "Март",
			keyStrength: "Сочувствие",
			keyWeakness: "Уязвимость",
		},
	};
	return signs[sign];
}
